// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAciQJNt4m6gnaObhBVZwW7LpctSppeHg8',
    appId: '1:70363574683:web:b93b53cd757feb2756f13e',
    messagingSenderId: '70363574683',
    projectId: 'talk-to-jesus-4fae7',
    authDomain: 'talk-to-jesus-4fae7.firebaseapp.com',
    storageBucket: 'talk-to-jesus-4fae7.firebasestorage.app',
    measurementId: 'G-N153MSDMVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYusHUaQ_2D2QpycUaxflOSFlebfPZajU',
    appId: '1:70363574683:android:2606dca1d7c93db656f13e',
    messagingSenderId: '70363574683',
    projectId: 'talk-to-jesus-4fae7',
    storageBucket: 'talk-to-jesus-4fae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3eaA2ylHQWpagnk0PmkU-Gi1xA0t70zk',
    appId: '1:982885317118:ios:ddd8a8796a3c365010a8af',
    messagingSenderId: '982885317118',
    projectId: 'talk-to-je',
    storageBucket: 'talk-to-je.firebasestorage.app',
    iosBundleId: 'com.example.talktojesus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3eaA2ylHQWpagnk0PmkU-Gi1xA0t70zk',
    appId: '1:982885317118:ios:ddd8a8796a3c365010a8af',
    messagingSenderId: '982885317118',
    projectId: 'talk-to-je',
    storageBucket: 'talk-to-je.firebasestorage.app',
    iosBundleId: 'com.example.talktojesus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAciQJNt4m6gnaObhBVZwW7LpctSppeHg8',
    appId: '1:70363574683:web:a2d288580db1ad5356f13e',
    messagingSenderId: '70363574683',
    projectId: 'talk-to-jesus-4fae7',
    authDomain: 'talk-to-jesus-4fae7.firebaseapp.com',
    storageBucket: 'talk-to-jesus-4fae7.firebasestorage.app',
    measurementId: 'G-SJ2R0L8N32',
  );
}
